# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- '*'

name: $(SourceBranchName)-$(Date:yyyyMMdd)$(Rev:.r)

variables:
  solution: 'apidoctools.sln'
  buildConfiguration: 'Release'
  mdocPath: 'bin/$(buildConfiguration)'

stages:
- stage: SDLCheck
  jobs:
  - job: SDLCheck
    pool:
      vmImage: 'windows-latest'

    steps:
    - task: CredScan@2
      displayName: Security - CredScan
      inputs:
        toolMajorVersion: 'V2'

    - task: CmdLine@2
      displayName: make prepare
      inputs:
        script: 'make prepare'

    - task: MSBuild@1
      displayName: MSBuild
      inputs:
        solution: '$(solution)'
        configuration: '$(buildConfiguration)'

    - task: BinSkim@3
      displayName: Security - BinSkim
      inputs:
        InputType: 'Basic'
        Function: 'analyze'
        AnalyzeTarget: '$(mdocPath)\*.dll;$(mdocPath)\*.exe;'

    - task: SdtReport@1
      displayName: Security - SdtReport
      inputs:
        AllTools: false
        CredScan: true
        BinSkim: true
        ToolLogsNotFoundAction: 'Standard'

    - task: PublishSecurityAnalysisLogs@2
      displayName: Security - Publish Scan Results
      inputs:
        ArtifactName: 'CodeAnalysisLogs'
        ArtifactType: 'Container'
        AllTools: true
        ToolLogsNotFoundAction: 'Standard'

    - task: TSAUpload@1
      inputs:
        tsaVersion: 'TsaV2'
        codebase: 'Existing'
        tsaEnvironment: 'PROD'
        codeBaseName: 'Docs_default'
        uploadBinSkim: true
        uploadCredScan: true
        uploadAsync: true

    - task: PostAnalysis@1
      displayName: Security - PostAnalysis
      inputs:
        AllTools: false
        CredScan: true
        BinSkim: true
        ToolLogsNotFoundAction: 'Standard'

    - task: ComponentGovernanceComponentDetection@0
      inputs:
        scanType: 'Register'
        verbosity: 'Verbose'
        alertWarningLevel: 'High'
